export const GET_ALL_REVIEWS_FOR_RESTAURANT = "GET_ALL_REVIEWS_FOR_RESTAURANT";
export const GET_RESTAURANT_REVIEWS_SUCCESS = "GET_RESTAURANT_REVIEWS_SUCCESS";
export const GET_RESTAURANT_REVIEWS_FAILURE = "GET_RESTAURANT_REVIEWS_FAILURE";
